
call plug#begin()

Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()


syntax on
set clipboard=unnamed

if has("autocmd")
  function! SetGuiFont()
    if has("gui_gtk") && !(has("win32") || has("win64"))
      let &guifont="Ubuntu Mono derivative Powerline 12"
    elseif has("win32") || has("win64")
      try
        let &guifont="DejaVu_Sans_Mono_for_Powerline:h14:cANSI:qDRAFT"
      catch
        " font does not exists, fall back to default
        let &guifont="Courier_New:h10:cANSI"
      endtry
    " optionally: add statements for other guis
    endif
  endfunction

  if !exists('#VimStartup#GuiEnter')
    augroup VimStartup
      au!
      autocmd GuiEnter * :call SetGuiFont()
    augroup end
  endif
endif

source $VIMRUNTIME/vimrc_example.vim

au GUIEnter * simalt ~x
set hls
set is
set cb=unnamed
set gfn=Fixedsys:h10
set ts=4
set sw=4
set si

inoremap { {}<Left>
inoremap {<CR> {<CR>}<Esc>O
inoremap {{ {
inoremap {} {}
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm() : "\<CR>"
inoremap <silent><expr> <c-space> coc#refresh()

autocmd filetype cpp nnoremap <F9> :w <bar> !g++ -std=c++14 % -o %:r -Wl,--stack,268435456<CR>
autocmd filetype cpp nnoremap <F10> :!%:r<CR>
autocmd filetype python nnoremap <F9> :w <bar> !py %<CR>
autocmd filetype cpp nnoremap <C-C> :s/^\(\s*\)/\1\/\/<CR> :s/^\(\s*\)\/\/\/\//\1<CR> $
autocmd filetype java nnoremap <F9> :w <bar> !javac %<CR>
autocmd filetype java nnoremap <F10> :w <bar> !java %<CR>
autocmd filetype java inoremap sout System.out.println("");<Left><Left><Left>
autocmd filetype java inoremap psvm public static void main(String[] args){<CR><CR>}

inoremap <space>t :-1read D:\ITSIEUCAPPRO\C++\Template\Mint.cpp <CR>/{<CR>o
nnoremap <leader>Mint :<C-u>pHello<CR>

"The following command puts the contents of Mint.cpp 
"under the cursor when the user types ":Mint" in normal mode.
command Mint :-1r D:\ITSIEUCAPPRO\C++\Template\Mint.cpp

set nu
augroup numbertoggle
    autocmd!
    autocmd BufEnter,FocusGained,InsertLeave * set rnu
    autocmd BufLeave,FocusLost,InsertEnter * set nornu
augroup END

set diffexpr=MyDiff()
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg1 = substitute(arg1, '!', '\!', 'g')
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg2 = substitute(arg2, '!', '\!', 'g')
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let arg3 = substitute(arg3, '!', '\!', 'g')
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      if empty(&shellxquote)
        let l:shxq_sav = ''
        set shellxquote&
      endif
      let cmd = '"' . $VIMRUNTIME . '\diff"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  let cmd = substitute(cmd, '!', '\!', 'g')
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3
  if exists('l:shxq_sav')
    let &shellxquote=l:shxq_sav
  endif
endfunction

set nobackup noswapfile noundofile autoread mouse=a
:set pumheight=20
autocmd VimResized * wincmd =

autocmd BufNewFile *.cpp $pu=strftime('// created: %Y-%m-%d %H:%M:%S')
autocmd BufNewFile *.cpp $pu=('// author: Nguyen Tung Duong')
autocmd BufNewFile *.cpp $pu=('')
autocmd BufNewFile *.cpp 4r D:\ITSIEUCAPPRO\C++\Template\createNewFile.cpp

